- name: Show ansible vars
  # hosts: cracking_baremetal
  hosts: cracking_vm
  become: true
  tasks:

    - name: Displaying check connection
      ansible.builtin.ping:
    # - name: Displaying ansible facts
    #   ansible.builtin.debug:
    #     var: ansible_facts

    # - name: Displaying host's hostvars
    #   ansible.builtin.debug:
    #     var: hostvars[inventory_hostname]

    # - name: Testing something
    #   ansible.builtin.debug:
    #     msg: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}"
      # when:
      #   - ansible_local is defined
      #   - ansible_local["gpuszz"] is defined
